### ISSUE TITLE
The health monitor doesn't work

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap-plugin-lib-py#2]
2016-11-18 20:18:45,977 - snap_plugin.v1.plugin - DEBUG - plugin start called..
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/jrcookli/.pyenv/versions/3.5.2/lib/python3.5/threading.py", line 914, in _bootstrap_inner
      self.run()
        File "/Users/jrcookli/.pyenv/versions/3.5.2/lib/python3.5/threading.py", line 862, in run
            self._target(*self._args, **self._kwargs)
            TypeError: _monitor() missing 1 required positional argument: 'shutting_down'

            {"Type": 0, "ErrorMessage": null, "ListenAddress": "127.0.0.1:64301", "State": 0, "PublicKey": null, "Meta": {"Type": 0, "Name
            ": "rand-py", "Unsecure": true, "RoutingStrategy": 0, "Exclusive": false, "RPCType": 2, "CacheTTL": null, "ConcurrencyCount":
            5, "RPCVersion": 1, "Version": 1}, "Token": null}
            (snap35)

**Comment by marcin-krolik** [comment]
Resolved #3
